antxetamedia/blobs/urls.py
from django.conf.urls import include, url

from .views import PodcastBlobList, admin_async_blob_upload


expressions = {
    'app_label': r'(?P<app_label>[\w-]+)',
    'model': r'(?P<model>[\w-]+)',
    'id': r'(?P<id>\d+)',
    'filename': r'(?P<filename>.+)',
}

news = [
    url(r'^{app_label}/{model}/{id}/$'.format(**expressions), PodcastBlobList.as_view(), name='podcast'),
    url(r'^admin/async_blob_upload/{filename}/$'.format(**expressions), admin_async_blob_upload,
        name='admin_async_blob_upload'),
]

urlpatterns = [url(r'^', include(news, namespace='blobs'))]

antxetamedia/news/urls.py
from django.conf.urls import include, url

from .views import NewsPodcastList, NewsPodcastDetail


expressions = {
    'newspodcast': r'(?P<slug>[\w-]+)',
}

news = [
    url(r'^$', NewsPodcastList.as_view(), name='list'),
    url(r'^{newspodcast}/$'.format(**expressions), NewsPodcastDetail.as_view(), name='detail'),
]

urlpatterns = [url(r'^', include(news, namespace='news'))]

antxetamedia/radio/urls.py
from django.conf.urls import include, url

from .views import RadioShowList, RadioShowPodcastList


expressions = {
    'radioshow': r'(?P<slug>[\w-]+)',
}

radio = [
    url(r'^$', RadioShowList.as_view(), name='list'),
    url(r'^{radioshow}/$'.format(**expressions), RadioShowPodcastList.as_view(), name='podcasts'),
]

urlpatterns = [url(r'^', include(radio, namespace='radio'))]

antxetamedia/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.i18n import javascript_catalog

from .feeds.views import BlobFeed


js_info_dict = {'packages': ['recurrence', 'antxetamedia']}

urlpatterns = [
    url(r'^', include('antxetamedia.frontpage.urls')),
    url(r'^news/', include('antxetamedia.news.urls')),
    url(r'^radio/', include('antxetamedia.radio.urls')),
    url(r'^projects/', include('antxetamedia.projects.urls')),
    url(r'^blobs/', include('antxetamedia.blobs.urls')),
    url(r'^f/', include('antxetamedia.flatpages.urls')),
    url(r'^events/', include('antxetamedia.events.urls')),
    url(r'^schedule/', include('antxetamedia.schedule.urls')),
    url(r'^archive/', include('antxetamedia.archive.urls')),
    url(r'^feed/$', BlobFeed(), name='feed'),

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^wkeditor/', include('ckeditor_uploader.urls')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='jsi18n'),
    url(r'^404/$', TemplateView.as_view(template_name='404.html')),
    url(r'^500/$', TemplateView.as_view(template_name='500.html')),
    url(r'^.well-known/acme-challenge/', include('django_acme.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

antxetamedia/radio/models.py
import json

from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _

from antxetamedia.shows.models import (AbstractCategory, AbstractProducer, AbstractShow, AbstractPodcast,
                                       CategoryManager, ProducerManager, ShowManager, PodcastQuerySet)


RADIOSHOWS_COOKIE = getattr(settings, 'RADIOSHOWS_COOKIE', 'radioshows')


class RadioCategory(AbstractCategory):
    objects = CategoryManager()

    class Meta:
        verbose_name = _('Radio category')
        verbose_name_plural = _('Radio categories')

    def get_absolute_url(self):
        return reverse('radio:list') + '?category=' + self.slug


class RadioProducer(AbstractProducer):
    objects = ProducerManager()

    class Meta:
        verbose_name = _('Radio producer')
        verbose_name_plural = _('Radio producers')

    def get_absolute_url(self):
        return reverse('radio:list') + '?producer=' + self.slug


class RadioShowQuerySet(models.QuerySet):
    def featured(self):
        return self.filter(featured=True)


class RadioShow(AbstractShow):
    objects = ShowManager.from_queryset(RadioShowQuerySet)()

    class Meta:
        verbose_name = _('Radio show')
        verbose_name_plural = _('Radio shows')

    category = models.ForeignKey(RadioCategory, null=True, blank=True, verbose_name=_('Category'))
    producer = models.ForeignKey(RadioProducer, verbose_name=_('Producer'))
    featured = models.BooleanField(_('Featured'), default=False)

    def get_absolute_url(self):
        return reverse('radio:podcasts', kwargs={'slug': self.slug})


class RadioPodcastQuerySet(PodcastQuerySet):
    def favourites(self, request):
        qs = self
        radioshows = request.COOKIES.get(RADIOSHOWS_COOKIE)
        if radioshows:
            radioshows = json.loads(radioshows)
            qs = qs.filter(show__pk__in=radioshows)
        return qs


class RadioPodcast(AbstractPodcast):
    objects = RadioPodcastQuerySet.as_manager()

    class Meta:
        ordering = ['-pub_date']
        verbose_name = _('Radio podcast')
        verbose_name_plural = _('Radio podcasts')

    show = models.ForeignKey(RadioShow, verbose_name=_('Show'))

    def get_absolute_url(self):
        return reverse('radio:podcasts', kwargs={'slug': self.show.slug})

antxetamedia/archive/views.py
from functools import reduce
from operator import add

from django.core.urlresolvers import reverse
from django.views.generic import ListView
from django.views.generic.edit import FormMixin
from django.utils.translation import ugettext as _

from watson import search
from watson.views import SearchMixin as WatsonSearchView

from antxetamedia.events.models import Event
from .filtersets import NewsPodcastFilterSet, RadioPodcastFilterSet, ProjectShowFilterSet
from .forms import EventForm


class SearchMixin(WatsonSearchView):
    template_name = 'archive/search.html'
    paginate_by = 10

    def get_tabs(self):
        newspodcast_filterset = NewsPodcastFilterSet(self.request.GET, prefix='news')
        radiopodcast_filterset = RadioPodcastFilterSet(self.request.GET, prefix='radio')
        projectshow_filterset = ProjectShowFilterSet(self.request.GET, prefix='projects')
        event_form = EventForm(self.request.GET, prefix='events')
        return [
            (_('Site-wide'), reverse('archive:search'), None),
            (_('News podcasts'), reverse('archive:news'), newspodcast_filterset.form),
            (_('Radio podcasts'), reverse('archive:radio'), radiopodcast_filterset.form),
            (_('Projects'), reverse('archive:projects'), projectshow_filterset.form),
            (_('Events'), reverse('archive:events'), event_form),
        ]

    def get_context_data(self, **kwargs):
        tabs = self.get_tabs()
        kwargs['tabs'] = tabs
        # Union of all media files
        kwargs['tab_media'] = reduce(add, [form.media for name, url, form in tabs if form is not None])
        return super(SearchMixin, self).get_context_data(**kwargs)


class SingleModelSearchMixin(SearchMixin):
    def get_base_queryset(self):
        return self.queryset

    def get_queryset(self):
        return search.filter(self.get_base_queryset(), self.query)


class SearchView(SearchMixin, ListView):
    pass


class FilterSetSeachMixin(SingleModelSearchMixin):
    prefix = None
    filterset_class = None

    def get_context_data(self, *args, **kwargs):
        kwargs['form'] = self.filterset_class(self.request.GET).form
        return super(FilterSetSeachMixin, self).get_context_data(*args, **kwargs)

    def get_queryset(self):
        filterset = self.filterset_class(self.request.GET,
                queryset=self.get_base_queryset(),
                prefix=self.prefix)
        return search.filter(filterset.qs, self.query)


class NewsPodcastSearchView(FilterSetSeachMixin, ListView):
    filterset_class = NewsPodcastFilterSet
    prefix = 'news'


class RadioPodcastSearchView(FilterSetSeachMixin, ListView):
    filterset_class = RadioPodcastFilterSet
    prefix = 'radio'


class ProjectShowSearchView(FilterSetSeachMixin, ListView):
    filterset_class = ProjectShowFilterSet
    prefix = 'projects'


class EventSearchView(FormMixin, SingleModelSearchMixin, ListView):
    form_class = EventForm
    prefix = 'events'

    def get(self, request, *args, **kwargs):
        self.query = self.get_query(request)
        self.object_list = self.get_queryset()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_base_queryset(self):
        return Event.objects.all()

    def get_initial(self):
        return self.request.GET

    def get_form_kwargs(self):
        kwargs = super(EventSearchView, self).get_form_kwargs()
        kwargs['data'] = self.request.GET
        return kwargs

    def form_valid(self, form):
        after = form.cleaned_data.get('after')
        before = form.cleaned_data.get('before')
        # NOTE: Little hack, event generator can be infinite, limit it to 10 pages
        count = self.paginate_by * 10
        qs = self.get_queryset()
        if (after, before) != (None, None):
            if None not in (after, before):
                qs = qs.between(after, before, count=count)
            elif after is not None:
                qs = qs.after(after, count=count)
            elif before is not None:
                qs = qs.before(before, count=count)
            qs = list({event for date, event in qs})
        self.object_list = qs
        return self.render_to_response(self.get_context_data(form=self.get_form()))

antxetamedia/blobs/views.py
import base64
import os

from django.contrib.admin.views.decorators import staff_member_required
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.http import HttpResponse
from django.http import JsonResponse
from django.views.generic import ListView

from .models import Blob


class PodcastBlobList(ListView):
    def get_queryset(self):
        qs = Blob.objects.with_content()
        qs = qs.filter(content_type__app_label=self.kwargs['app_label'],
                       content_type__model=self.kwargs['model'],
                       object_id=self.kwargs['id'])
        qs = qs.order_by('position')
        qs = qs.select_related('content_type').prefetch_related('content_object')
        return qs

    def get_blob_data(self, blob):
        return {
            'pk': blob.pk,
            'podcast': blob.content_object.get_absolute_url(),
            'title': str(blob),
            'image': blob.content_object.image.url if blob.content_object.image else None,
            'url': blob.link,
        }

    def get_context_data(self, **kwargs):
        kwargs['blob_list'] = [self.get_blob_data(blob) for blob in self.object_list]
        return super(PodcastBlobList, self).get_context_data(**kwargs)

    def render_to_response(self, context, **response_kwargs):
        return JsonResponse({'blobs': context['blob_list']})


@staff_member_required
def admin_async_blob_upload(request, filename):
    filename = base64.b64decode(filename).decode('utf-8', 'ignore')
    path = os.path.join(Blob._meta.get_field('local').get_directory_name(), filename)
    return HttpResponse(default_storage.save(path, ContentFile(request.body)), 'text/plain')

antxetamedia/events/views.py
from django.views.generic import ListView, DetailView

from .models import Event


class EventMixin(object):
    model = Event


class EventList(EventMixin, ListView):
    template_name = 'events/event_list.html'
    context_object_name = 'event_list'
    paginate_by = 10

    def get_queryset(self):
        # NOTE: Little hack, event generator can be infinite, limit it to 10 pages
        return list(Event.objects.upcoming(count=(self.paginate_by * 10)))


class EventDetail(EventMixin, DetailView):
    pass

antxetamedia/feeds/views.py
import heapq

from django.contrib.syndication.views import Feed, add_domain
from django.core.urlresolvers import reverse
from django.utils.feedgenerator import Atom1Feed, Enclosure
from django.utils.translation import ugettext_lazy as _

from antxetamedia.news.models import NewsPodcast
from antxetamedia.radio.models import RadioPodcast


class BlobFeed(Feed):
    feed_type = Atom1Feed
    title = _('Antxetamedia')
    description = _('Latest news and radio podcasts from Antxetamedia')
    link = '/'
    author_name = 'Antxeta Irratia'

    def get_feed(self, obj, request):
        self.request = request
        return super(BlobFeed, self).get_feed(obj, request)

    def feed_url(self):
        return reverse('feed')

    def items(self):
        # Blobs do not have a creation timestamp. We must therefore get the
        # podcasts, order them, and get their related blobs
        newspodcasts = NewsPodcast.objects.published()[:10].iterator()
        radiopodcasts = RadioPodcast.objects.published()[:10].iterator()
        # Respect the order of each queryset, only order them when merging
        news_dates = ((n.pub_date, n) for n in newspodcasts)
        radio_dates = ((r.pub_date, r) for r in radiopodcasts)
        podcast_dates = heapq.merge(news_dates, radio_dates)
        return (p[1] for p in podcast_dates)

    def item_title(self, item):
        return str(item)

    def item_description(self, item):
        return item.description

    def item_link(self, item):
        return item.get_absolute_url()

    def item_pubdate(self, item):
        return item.pub_date

    def item_author_name(self, item):
        return item.show.name

    def item_author_link(self, item):
        return item.show.get_absolute_url()

    def item_enclosures(self, item):
        for blob in item.blob_set.all():
            if blob.link:
                # add_domain adds the domain only if the url doesn't already have one
                link = add_domain(self.request.get_host(), blob.link, self.request.is_secure())
                # When an enclosure's size cannot be determined, a publisher should use a length of 0.
                yield Enclosure(link, length='0', mime_type="audio/mpeg")

antxetamedia/frontpage/views.py
import json

from django.conf import settings
from django.core.urlresolvers import reverse
from django.views.generic import RedirectView, TemplateView, FormView

from antxetamedia.news.models import NewsPodcast, NewsCategory
from antxetamedia.radio.models import RadioPodcast, RadioShow
from antxetamedia.events.models import Event
from antxetamedia.widgets.models import Widget

from .forms import ConfigureFrontPageForm


class FrontPage(TemplateView):
    template_name = 'frontpage/frontpage.html'

    def get_context_data(self, *args, **kwargs):
        NEWSPODCASTS = getattr(settings, 'FRONTPAGE_NEWSPODCASTS', 10)
        RADIOPODCASTS = getattr(settings, 'FRONTPAGE_RADIOPODCASTS', 5)
        EVENTS = getattr(settings, 'FRONTPAGE_EVENTS', 5)
        kwargs['newspodcast_list'] = NewsPodcast.objects.favourites(self.request)[:NEWSPODCASTS]
        kwargs['radiopodcast_list'] = RadioPodcast.objects.favourites(self.request)[:RADIOPODCASTS]
        kwargs['event_list'] = Event.objects.upcoming(count=EVENTS)
        kwargs['widget_list'] = Widget.objects.all()
        return super(FrontPage, self).get_context_data(*args, **kwargs)


class ConfigureFrontPage(FormView):
    form_class = ConfigureFrontPageForm
    template_name = 'frontpage/configure.html'
    cookies = {}

    def get_initial(self):
        newscategories = self.request.COOKIES.get(settings.NEWSCATEGORIES_COOKIE)
        if newscategories:
            newscategories = json.loads(newscategories)
        else:
            newscategories = NewsCategory.objects.values_list('pk', flat=True)

        radioshows = self.request.COOKIES.get(settings.RADIOSHOWS_COOKIE)
        if radioshows:
            radioshows = json.loads(radioshows)
        else:
            radioshows = RadioShow.objects.values_list('pk', flat=True)

        return {'newscategories': newscategories, 'radioshows': radioshows}

    def form_valid(self, form):
        newscategories = list(form.cleaned_data['newscategories'].values_list('pk', flat=True))
        self.cookies[settings.NEWSCATEGORIES_COOKIE] = json.dumps(newscategories)
        radioshows = list(form.cleaned_data['radioshows'].values_list('pk', flat=True))
        self.cookies[settings.RADIOSHOWS_COOKIE] = json.dumps(radioshows)
        return super(ConfigureFrontPage, self).form_valid(form)

    def get_context_data(self, *args, **kwargs):
        kwargs['NEWSCATEGORIES_COOKIE'] = settings.NEWSCATEGORIES_COOKIE
        kwargs['RADIOSHOWS_COOKIE'] = settings.RADIOSHOWS_COOKIE
        return super(ConfigureFrontPage, self).get_context_data(*args, **kwargs)

    def get_success_url(self):
        return reverse('frontpage')

    def dispatch(self, request, *args, **kwargs):
        response = super(ConfigureFrontPage, self).dispatch(request, *args, **kwargs)
        for key, value in self.cookies.items():
            response.set_cookie(key, value)
        return response


class ResetFrontPageConfiguration(RedirectView):
    permanent = False

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)

    def get_redirect_url(self):
        return reverse('frontpage')

    def dispatch(self, request, *args, **kwargs):
        response = super(ResetFrontPageConfiguration, self).dispatch(request, *args, **kwargs)
        response.delete_cookie(settings.NEWSCATEGORIES_COOKIE)
        response.delete_cookie(settings.RADIOSHOWS_COOKIE)
        return response

antxetamedia/templates/radio/radiopodcast_list.html
{% extends 'base.html' %}
{% load i18n compress thumbnail static %}

{% block title %}{{ radioshow }}{% endblock title %}

{% block tail_extra_js %}
{% compress js %}
<script src="{% static 'js/folders.js' %}" type="text/javascript" charset="utf-8"></script>
{% endcompress js %}
{% endblock tail_extra_js %}


{% block content %}
<article>
  <div class="articleDetails">
    {% thumbnail radioshow.image "500" as image %}
    <img src="{{ image.url }}"/>
    {% empty %}
    <img src="{% static 'images/radio.svg' %}" alt="radio"/>
    {% endthumbnail %}
  </div>
  <div class="text">
    {% if radioshow.category %}
    <h2 class="category"><a href="{{ radioshow.category.get_absolute_url }}">{{ radioshow.category }}</a></h2>
    {% endif %}
    <p class="date"><a href="{{ radioshow.producer.get_absolute_url }}">{{ radioshow.producer }}</a></p>
    <h1>{{ radioshow }}</h1>
    {{ radioshow.description | safe }}
    <table class="podcastList">
      <thead>
        <th>{% trans 'Podcast' %}</th>
        <th></th>
        <th>{% trans 'Date' %}</th>
      </thead>
      <tbody>
        {% for radiopodcast in radiopodcast_list %}
        <tr>
          <td class="folder">
            <span class="podcastTitle">{{ radiopodcast }}</span>
            <div class="folderContent">
              <div class="articleDetails">
                {% thumbnail radiopodcast.image "500" as image %}
                <img class="podcastImage" src="{{ image.url }}" />
                {% endthumbnail %}
              </div>
              <div class="text">
                <span class="podcastText">{{ radiopodcast.description | safe }}</span>
              </div>
            </div>
          </td>
          <td class="poscastControls">{% include 'podcast_control.html' with podcast=radiopodcast %}</td>
          <td class="podcastDate">{{ radiopodcast.pub_date|date:"Y-m-d" }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% include 'pagination.html' with object_list=radiopodcast_list %}
  </div>
</article>
{% endblock content %}

antxetamedia/templates/radio/radioshow_detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{{ radioshow }}{% endblock title %}

{% block content %}
<article>
  <div class="articleDetails">
    {% if radioshow.image %}
    <img src="{{ radioshow.image.url }}"/>
    {% endif %}
  </div>
  <p class="date">{{ radioshow.producer }}</p>
  <h2 class="category">{{ radioshow.category }}</h2>
  <h1>{{ radioshow }}</h1>
  {{ radioshow.description | safe }}
  <table class="podcastList">
    <tr>
      <th>{% trans 'Podcast' %}</th>
      <th></th>
      <th>{% trans 'Date' %}</th>
    </tr>
    {% for radiopodcast in radioshow.radiopodcast_set.select_related %}
    <tr>
      <td>{{ radiopodcast }}</td>
      <td id="podcastPlay">
        <i class="fa fa-play"></i>
        <i class="fa fa-plus"></i>
        <i class="fa fa-share"></i>
        <i class="fa fa-download"></i>
      </td>
      <td id="podcastDate">{{ radiopodcast.pub_date|date:"Y-m-d" }}</td>
    </tr>
    <tr id="podcastDescription">
      <td colspan="3">{% if radiopodcast.image %}<img id="podcastImage"
        src="{{ radiopodcast.image.ul }}"/>{% endif %}
        <span id="podcastText">{{ radiopodcast.description | safe }}</span></td>
    </tr>
    {% endfor %}
  </table>
{% endblock content %}

antxetamedia/templates/radio/radioshow_list.html
{% extends 'base.html' %}
{% load static i18n thumbnail compress %}

{% block title %}
{% trans 'Radio Shows' %}
{% endblock title %}

{% block tail_extra_js %}
{% compress js %}
<script src="{% static 'js/radio_filter.js' %}" type="text/javascript" charset="utf-8"></script>
{% endcompress js %}
{% endblock tail_extra_js %}

{% block aside %}
<form class="cross_out" method="get" action=".">
  {{ form }}
</form>
{% endblock aside %}

{% block content %}
<ul id="radioShows" class="cardList">
  {% for radioshow in radioshow_list.featured %}
  <li class="card featured">
    <h1><a href="{{ radioshow.get_absolute_url }}">{{ radioshow }}</a></h1>
    {% if radioshow.category %}
    <h2 class="category"><a href="{{ radioshow.category.get_absolute_url }}">{{ radioshow.category }}</a></h2>
    {% endif %}
    <p class="date"><a href="{{ radioshow.producer.get_absolute_url }}">{{ radioshow.producer }}</a></p>

    <a href="{{ radioshow.get_absolute_url }}">
      {% thumbnail radioshow.image "500" as image %}
      <img src="{{ image.url }}"/>
      {% empty %}
      <img src="{% static 'images/radio.svg' %}" alt="radio"/>
      {% endthumbnail %}
    </a>
  </li>
  {% endfor %}

  {% for radioshow in radioshow_list %}
  <li class="card" data-producer="{{ radioshow.producer.slug }}" data-category="{{ radioshow.category.slug }}">
    <h1><a href="{{ radioshow.get_absolute_url }}">{{ radioshow }}</a></h1>
    {% if radioshow.category %}
    <h2 class="category"><a href="{{ radioshow.category.get_absolute_url }}">{{ radioshow.category }}</a></h2>
    {% endif %}
    <p class="date"><a href="{{ radioshow.producer.get_absolute_url }}">{{ radioshow.producer }}</a></p>

    <a href="{{ radioshow.get_absolute_url }}">
      {% thumbnail radioshow.image "500" as image %}
      <img src="{{ image.url }}"/>
      {% empty %}
      <img src="{% static 'images/radio.svg' %}" alt="radio"/>
      {% endthumbnail %}
    </a>
  </li>
  {% endfor %}
</ul>
{% endblock content %}