antxetamedia/archive/urls.py
from django.conf.urls import include, url

from . import views


archive = [
    url(r'^$', views.SearchView.as_view(), name='search'),
    url(r'^news/$', views.NewsPodcastSearchView.as_view(), name='news'),
    url(r'^radio/$', views.RadioPodcastSearchView.as_view(), name='radio'),
    url(r'^projects/$', views.ProjectShowSearchView.as_view(), name='projects'),
    url(r'^events/$', views.EventSearchView.as_view(), name='events'),
]

urlpatterns = [url(r'^', include(archive, namespace='archive'))]

antxetamedia/blobs/urls.py
from django.conf.urls import include, url

from .views import PodcastBlobList, admin_async_blob_upload


expressions = {
    'app_label': r'(?P<app_label>[\w-]+)',
    'model': r'(?P<model>[\w-]+)',
    'id': r'(?P<id>\d+)',
    'filename': r'(?P<filename>.+)',
}

news = [
    url(r'^{app_label}/{model}/{id}/$'.format(**expressions), PodcastBlobList.as_view(), name='podcast'),
    url(r'^admin/async_blob_upload/{filename}/$'.format(**expressions), admin_async_blob_upload,
        name='admin_async_blob_upload'),
]

urlpatterns = [url(r'^', include(news, namespace='blobs'))]

antxetamedia/events/urls.py
from django.conf.urls import include, url

from .views import EventList, EventDetail


expressions = {
    'event': r'(?P<slug>[\w-]+)',
}

events = [
    url(r'^$', EventList.as_view(), name='list'),
    url(r'^{event}/$'.format(**expressions), EventDetail.as_view(), name='detail'),
]

urlpatterns = [url(r'^', include(events, namespace='events'))]

antxetamedia/news/urls.py
from django.conf.urls import include, url

from .views import NewsPodcastList, NewsPodcastDetail


expressions = {
    'newspodcast': r'(?P<slug>[\w-]+)',
}

news = [
    url(r'^$', NewsPodcastList.as_view(), name='list'),
    url(r'^{newspodcast}/$'.format(**expressions), NewsPodcastDetail.as_view(), name='detail'),
]

urlpatterns = [url(r'^', include(news, namespace='news'))]

antxetamedia/projects/urls.py
from django.conf.urls import include, url

from .views import ProjectShowList, ProjectShowDetail


expressions = {
    'projectshow': r'(?P<slug>[\w-]+)',
}

radio = [
    url(r'^$', ProjectShowList.as_view(), name='list'),
    url(r'^{projectshow}/$'.format(**expressions), ProjectShowDetail.as_view(), name='detail'),
]

urlpatterns = [url(r'^', include(radio, namespace='projects'))]

antxetamedia/radio/urls.py
from django.conf.urls import include, url

from .views import RadioShowList, RadioShowPodcastList


expressions = {
    'radioshow': r'(?P<slug>[\w-]+)',
}

radio = [
    url(r'^$', RadioShowList.as_view(), name='list'),
    url(r'^{radioshow}/$'.format(**expressions), RadioShowPodcastList.as_view(), name='podcasts'),
]

urlpatterns = [url(r'^', include(radio, namespace='radio'))]

antxetamedia/schedule/urls.py
from django.conf.urls import include, url

from .views import BroadcastList


schedule = [
    url(r'^$', BroadcastList.as_view(), name='list'),
]

urlpatterns = [url(r'^', include(schedule, namespace='schedule'))]

antxetamedia/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.i18n import javascript_catalog

from .feeds.views import BlobFeed


js_info_dict = {'packages': ['recurrence', 'antxetamedia']}

urlpatterns = [
    url(r'^', include('antxetamedia.frontpage.urls')),
    url(r'^news/', include('antxetamedia.news.urls')),
    url(r'^radio/', include('antxetamedia.radio.urls')),
    url(r'^projects/', include('antxetamedia.projects.urls')),
    url(r'^blobs/', include('antxetamedia.blobs.urls')),
    url(r'^f/', include('antxetamedia.flatpages.urls')),
    url(r'^events/', include('antxetamedia.events.urls')),
    url(r'^schedule/', include('antxetamedia.schedule.urls')),
    url(r'^archive/', include('antxetamedia.archive.urls')),
    url(r'^feed/$', BlobFeed(), name='feed'),

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^wkeditor/', include('ckeditor_uploader.urls')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='jsi18n'),
    url(r'^404/$', TemplateView.as_view(template_name='404.html')),
    url(r'^500/$', TemplateView.as_view(template_name='500.html')),
    url(r'^.well-known/acme-challenge/', include('django_acme.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

antxetamedia/blobs/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models, transaction
from django.core.exceptions import ValidationError
from django.contrib.contenttypes.fields import GenericForeignKey
from django.utils.six import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone


@python_2_unicode_compatible
class Account(models.Model):
    class Meta:
        verbose_name = _('Account')
        verbose_name_plural = _('Accounts')

    name = models.CharField(_('Name'), max_length=64)
    username = models.CharField(_('Username'), max_length=256)
    password = models.CharField(_('Password'), max_length=256)

    def __str__(self):
        return self.name


class BlobQuerySet(models.QuerySet):
    def with_content(self):
        query = ((models.Q(remote__isnull=False) & ~models.Q(remote='')) |
                 (models.Q(local__isnull=False) & ~models.Q(local='')))
        return self.filter(query)


@python_2_unicode_compatible
class Blob(models.Model):
    objects = BlobQuerySet.as_manager()

    class Meta:
        ordering = ['-created']
        verbose_name = _('Audio blob')
        verbose_name_plural = _('Audio blobs')

    content_type = models.ForeignKey('contenttypes.contenttype')
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    created = models.DateTimeField(_('Created'), auto_now_add=True, editable=False)
    position = models.PositiveIntegerField(_('Position'), default=0)

    local = models.FileField(_('Local file'), upload_to='blobs', null=True, blank=True, max_length=512,
                             help_text=_("If set, the file will be uploaded to the remote storage and the link will "
                                         "be set at the remote field."))
    remote = models.CharField(_('Remote file'), max_length=512, null=True, blank=True)
    account = models.ForeignKey(Account, verbose_name=_('Account'))

    def __str__(self):
        return '{self.content_object} - #{self.position}'.format(self=self)

    @property
    def is_uploaded(self):
        return bool(not self.local and self.remote)

    @property
    def link(self):
        if self.local:
            return self.local.url
        if self.remote:
            return self.remote
        return ''

    def clean(self):
        if not self.local and not self.remote:
            raise ValidationError(_("Blobs should have either a local or a remote file."))


@python_2_unicode_compatible
class BlobUpload(models.Model):
    PENDING = 0
    UPLOADING = 1
    SUCCEEDED = 2
    FAILED = 3
    STATES = [
        (PENDING, _('Pending')),
        (UPLOADING, _('Uploading')),
        (SUCCEEDED, _('Succeeded')),
        (FAILED, _('Failed')),
    ]

    class Meta:
        verbose_name = _('Blob upload')
        verbose_name_plural = _('Blob uploads')

    blob = models.ForeignKey(Blob, verbose_name=_('Blob'))
    state = models.PositiveSmallIntegerField(_('State'), choices=STATES, default=PENDING)
    started = models.DateTimeField(_('Start time'), null=True, blank=True)
    ended = models.DateTimeField(_('End time'), null=True, blank=True)
    traceback = models.TextField(_('Traceback'), blank=True)

    def __str__(self):
        return _('{blob} upload').format(blob=self.blob)

    def has_succeeded(self):
        if self.state in (self.SUCCEEDED, self.FAILED):
            return self.state == self.SUCCEEDED
        return None

    def is_uploading(self):
        self.started = timezone.now()
        self.state = self.UPLOADING
        self.save()

    def is_successful(self, remote):
        with transaction.atomic():
            self.ended = timezone.now()
            self.state = self.SUCCEEDED
            self.save()
            self.blob.remote = remote
            self.blob.local.delete()
            self.blob.save()

    def is_unsuccessful(self, traceback=None):
        self.ended = timezone.now()
        self.state = self.FAILED
        self.traceback = traceback
        self.save()

antxetamedia/archive/views.py
from functools import reduce
from operator import add

from django.core.urlresolvers import reverse
from django.views.generic import ListView
from django.views.generic.edit import FormMixin
from django.utils.translation import ugettext as _

from watson import search
from watson.views import SearchMixin as WatsonSearchView

from antxetamedia.events.models import Event
from .filtersets import NewsPodcastFilterSet, RadioPodcastFilterSet, ProjectShowFilterSet
from .forms import EventForm


class SearchMixin(WatsonSearchView):
    template_name = 'archive/search.html'
    paginate_by = 10

    def get_tabs(self):
        newspodcast_filterset = NewsPodcastFilterSet(self.request.GET, prefix='news')
        radiopodcast_filterset = RadioPodcastFilterSet(self.request.GET, prefix='radio')
        projectshow_filterset = ProjectShowFilterSet(self.request.GET, prefix='projects')
        event_form = EventForm(self.request.GET, prefix='events')
        return [
            (_('Site-wide'), reverse('archive:search'), None),
            (_('News podcasts'), reverse('archive:news'), newspodcast_filterset.form),
            (_('Radio podcasts'), reverse('archive:radio'), radiopodcast_filterset.form),
            (_('Projects'), reverse('archive:projects'), projectshow_filterset.form),
            (_('Events'), reverse('archive:events'), event_form),
        ]

    def get_context_data(self, **kwargs):
        tabs = self.get_tabs()
        kwargs['tabs'] = tabs
        # Union of all media files
        kwargs['tab_media'] = reduce(add, [form.media for name, url, form in tabs if form is not None])
        return super(SearchMixin, self).get_context_data(**kwargs)


class SingleModelSearchMixin(SearchMixin):
    def get_base_queryset(self):
        return self.queryset

    def get_queryset(self):
        return search.filter(self.get_base_queryset(), self.query)


class SearchView(SearchMixin, ListView):
    pass


class FilterSetSeachMixin(SingleModelSearchMixin):
    prefix = None
    filterset_class = None

    def get_context_data(self, *args, **kwargs):
        kwargs['form'] = self.filterset_class(self.request.GET).form
        return super(FilterSetSeachMixin, self).get_context_data(*args, **kwargs)

    def get_queryset(self):
        filterset = self.filterset_class(self.request.GET,
                queryset=self.get_base_queryset(),
                prefix=self.prefix)
        return search.filter(filterset.qs, self.query)


class NewsPodcastSearchView(FilterSetSeachMixin, ListView):
    filterset_class = NewsPodcastFilterSet
    prefix = 'news'


class RadioPodcastSearchView(FilterSetSeachMixin, ListView):
    filterset_class = RadioPodcastFilterSet
    prefix = 'radio'


class ProjectShowSearchView(FilterSetSeachMixin, ListView):
    filterset_class = ProjectShowFilterSet
    prefix = 'projects'


class EventSearchView(FormMixin, SingleModelSearchMixin, ListView):
    form_class = EventForm
    prefix = 'events'

    def get(self, request, *args, **kwargs):
        self.query = self.get_query(request)
        self.object_list = self.get_queryset()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_base_queryset(self):
        return Event.objects.all()

    def get_initial(self):
        return self.request.GET

    def get_form_kwargs(self):
        kwargs = super(EventSearchView, self).get_form_kwargs()
        kwargs['data'] = self.request.GET
        return kwargs

    def form_valid(self, form):
        after = form.cleaned_data.get('after')
        before = form.cleaned_data.get('before')
        # NOTE: Little hack, event generator can be infinite, limit it to 10 pages
        count = self.paginate_by * 10
        qs = self.get_queryset()
        if (after, before) != (None, None):
            if None not in (after, before):
                qs = qs.between(after, before, count=count)
            elif after is not None:
                qs = qs.after(after, count=count)
            elif before is not None:
                qs = qs.before(before, count=count)
            qs = list({event for date, event in qs})
        self.object_list = qs
        return self.render_to_response(self.get_context_data(form=self.get_form()))

antxetamedia/blobs/views.py
import base64
import os

from django.contrib.admin.views.decorators import staff_member_required
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.http import HttpResponse
from django.http import JsonResponse
from django.views.generic import ListView

from .models import Blob


class PodcastBlobList(ListView):
    def get_queryset(self):
        qs = Blob.objects.with_content()
        qs = qs.filter(content_type__app_label=self.kwargs['app_label'],
                       content_type__model=self.kwargs['model'],
                       object_id=self.kwargs['id'])
        qs = qs.order_by('position')
        qs = qs.select_related('content_type').prefetch_related('content_object')
        return qs

    def get_blob_data(self, blob):
        return {
            'pk': blob.pk,
            'podcast': blob.content_object.get_absolute_url(),
            'title': str(blob),
            'image': blob.content_object.image.url if blob.content_object.image else None,
            'url': blob.link,
        }

    def get_context_data(self, **kwargs):
        kwargs['blob_list'] = [self.get_blob_data(blob) for blob in self.object_list]
        return super(PodcastBlobList, self).get_context_data(**kwargs)

    def render_to_response(self, context, **response_kwargs):
        return JsonResponse({'blobs': context['blob_list']})


@staff_member_required
def admin_async_blob_upload(request, filename):
    filename = base64.b64decode(filename).decode('utf-8', 'ignore')
    path = os.path.join(Blob._meta.get_field('local').get_directory_name(), filename)
    return HttpResponse(default_storage.save(path, ContentFile(request.body)), 'text/plain')

antxetamedia/events/views.py
from django.views.generic import ListView, DetailView

from .models import Event


class EventMixin(object):
    model = Event


class EventList(EventMixin, ListView):
    template_name = 'events/event_list.html'
    context_object_name = 'event_list'
    paginate_by = 10

    def get_queryset(self):
        # NOTE: Little hack, event generator can be infinite, limit it to 10 pages
        return list(Event.objects.upcoming(count=(self.paginate_by * 10)))


class EventDetail(EventMixin, DetailView):
    pass

antxetamedia/feeds/views.py
import heapq

from django.contrib.syndication.views import Feed, add_domain
from django.core.urlresolvers import reverse
from django.utils.feedgenerator import Atom1Feed, Enclosure
from django.utils.translation import ugettext_lazy as _

from antxetamedia.news.models import NewsPodcast
from antxetamedia.radio.models import RadioPodcast


class BlobFeed(Feed):
    feed_type = Atom1Feed
    title = _('Antxetamedia')
    description = _('Latest news and radio podcasts from Antxetamedia')
    link = '/'
    author_name = 'Antxeta Irratia'

    def get_feed(self, obj, request):
        self.request = request
        return super(BlobFeed, self).get_feed(obj, request)

    def feed_url(self):
        return reverse('feed')

    def items(self):
        # Blobs do not have a creation timestamp. We must therefore get the
        # podcasts, order them, and get their related blobs
        newspodcasts = NewsPodcast.objects.published()[:10].iterator()
        radiopodcasts = RadioPodcast.objects.published()[:10].iterator()
        # Respect the order of each queryset, only order them when merging
        news_dates = ((n.pub_date, n) for n in newspodcasts)
        radio_dates = ((r.pub_date, r) for r in radiopodcasts)
        podcast_dates = heapq.merge(news_dates, radio_dates)
        return (p[1] for p in podcast_dates)

    def item_title(self, item):
        return str(item)

    def item_description(self, item):
        return item.description

    def item_link(self, item):
        return item.get_absolute_url()

    def item_pubdate(self, item):
        return item.pub_date

    def item_author_name(self, item):
        return item.show.name

    def item_author_link(self, item):
        return item.show.get_absolute_url()

    def item_enclosures(self, item):
        for blob in item.blob_set.all():
            if blob.link:
                # add_domain adds the domain only if the url doesn't already have one
                link = add_domain(self.request.get_host(), blob.link, self.request.is_secure())
                # When an enclosure's size cannot be determined, a publisher should use a length of 0.
                yield Enclosure(link, length='0', mime_type="audio/mpeg")

antxetamedia/projects/views.py
from django.views.generic import ListView, DetailView

from .models import ProjectShow


class ProjectShowMixin(object):
    queryset = ProjectShow.objects.order_by('-creation_date')


class ProjectShowList(ProjectShowMixin, ListView):
    paginate_by = 20


class ProjectShowDetail(ProjectShowMixin, DetailView):
    pass

antxetamedia/templates/base.html
{% load i18n static compress %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% trans 'Frontpage' %}{% endblock title %} - Antxetamedia</title>
    <meta charset="utf-8">
    <meta name="author" content="Antxeta Irratia">
    <meta name="description" content="Antxeta Irratia Euskara hutsez emititzen
    duen Bidasoaldeko irratia da, Hendaian egoitza duena.">
    <meta name="keywords" content="antxeta, irratia, euskara, hendaia,
    bidasoaldea">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% compress css %}
    <link rel="stylesheet" type="text/x-sass" href="{% static 'css/main.sass' %}" />
    {% endcompress css %}

    {% block extra_css %}
    {% endblock extra_css %}

    {% block head_extra_js %}
    {% endblock head_extra_js %}

    {% compress js %}
    <script src="{% static 'bower_components/angular/angular.js' %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static 'bower_components/ngDraggable/ngDraggable.js' %}" type="text/javascript" charset="utf-8"></script>
    {% endcompress js %}

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-53395871-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-53395871-2');
    </script>

  </head>
  <body>
    <section id="mainNav">
      <nav id="menu">
        <ul>
          <li><a href="{% url 'frontpage' %}">{% trans 'Frontpage' %}</a></li>
          <li><a href="{% url 'news:list' %}">{% trans 'News' %}</a></li>
          <li><a href="{% url 'radio:list' %}">{% trans 'Radio' %}</a></li>
          <li><a href="{% url 'projects:list' %}">{% trans 'Projects' %}</a></li>
          <li><a href="{% url 'events:list' %}">{% trans 'Events' %}</a></li>
          <li><a href="{% url 'archive:search' %}">{% trans 'Archive' %}</a></li>
          <li><a href="{% url 'radio:podcasts' slug='hitzaldiak' %}">{% trans 'Talks' %}</a></li>
          <li><a href="{% url 'schedule:list' %}">{% trans 'Schedule' %}</a></li>
          {% for flatpage in menu_flatpage_list %}
          <li><a href="{{ flatpage.get_absolute_url }}">{{ flatpage }}</a></li>
          {% endfor %}
        </ul>
      </nav>
      <nav id="rss">
        <a href="{% url 'feed' %}"><i class="fa fa-rss"></i></a>
      </nav>
    </section>
    <header>
      <div id="logo">
        <a href="/"><img src="{% static 'images/antxetairratia.svg' %}" alt="antxetamedia" /></a>
        <div id="subtitle">
          <div id="live"><a>{% trans 'LIVE' %}</a></div>
          <div id="broadcast"><a>90.5/89.7/105.8</a></div>
        </div>
      </div>
      {% include "player.html" %}

      {% block configure %}
      {% endblock configure %}

    </header>

    <div id="wrap">
      <section id="mainContent">
        {% block content %}
        {% endblock content %}
      </section>
      <aside>
        {% block aside %}
        {% endblock aside %}
      </aside>
    </div>

    <footer id="mainFooter">
      <div id="license">
        <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img src="{% static 'images/by-sa.svg' %}" alt="Creative Commons by" /></a>
        <span xmlns:dct="http://purl.org/dc/terms/"
          property="dct:title"><a
            href="http://antxetamedia.eus/">antxetamedia.eus</a></span>-eko edukia, <a
          xmlns:cc="http://creativecommons.org/ns#" href="antxetamedia.eus"
          property="cc:attributionName" rel="cc:attributionURL">Antxeta
          Irratia</a>k ekoiztutakoa, <a rel="license"  href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons
          Aitortu Partekatu Berdin 4.0 Nazioartekoa baimen baten mende dago</a>
      </div>
      <div id="sponsors">
        <a href="http://antxetamedia.eus/">
          <img src="{% static 'images/antxeta.png' %}" alt="Antxeta Irratia" />
        </a>
        <a href="http://pausumedia.com/">
          <img src="{% static 'images/pausumedia.svg' %}" alt="Pausumedia" />
        </a>
        <a href="http://euskalirratiak.eus/">
          <img src="{% static 'images/euskalirratiak.png' %}" alt="Euskal Irratiak" />
        </a>
        <a href="http://euskadi.eus/">
          <img src="{% static 'images/jaurlaritza.svg' %}" alt="Eusko Jaurlaritza" />
        </a>
        <a href="http://gipuzkoa.eus/">
          <img src="{% static 'images/gfa.png' %}" alt="Gipuzkoako Foru Aldundia" />
        </a>
      </div>
    </footer>

    {% compress js %}
    <script src="{% static 'js/events.js' %}" type="text/javascript" charset="utf-8"></script>
    <script type="text/javascript" charset=utf-8">
      window.STREAM_BLOB = {
          pk: 0,
          podcast: "/",
          title: "{% trans 'Antxeta Irratia live' %}",
          image: "{% static 'images/radio.svg' %}",
          url: "http://217.160.91.69:8000/antxetairratia.mp3",
          isStream: true,
      };
    </script>
    <script src="{% static 'js/player.js' %}" type="text/javascript" charset="utf-8"></script>
    {% endcompress js %}
    {% block tail_extra_js %}
    {% endblock tail_extra_js %}
  </body>
</html>

antxetamedia/templates/pagination.html
{% load i18n url_replace %}

{% if is_paginated %}
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?{% url_replace page=page_obj.previous_page_number %}">{% trans 'Previous' %}</a>
    {% endif %}
    <span class="current">
      {% blocktrans with current=page_obj.number total=page_obj.paginator.num_pages %}
      {{ current }} page of {{ total }}
      {% endblocktrans %}
    </span>
    {% if page_obj.has_next %}
    <a href="?{% url_replace page=page_obj.next_page_number %}">{% trans 'Next' %}</a>
    {% endif %}
  </span>
</div>
{% endif %}

antxetamedia/templates/player.html
{% load i18n static compress %}
<div id="player" ng-app="player" ng-controller="playerController" ng-cloak>
  <progress id="playerProgress" max="100"
    value="[[ progress || 0 ]]"
    ng-click="setProgress($event)"
    title="{% trans 'Progress' %}"></progress>
  <div id="playerWrap">
    <div class="detail playerImage" ng-if="blob.image"
      ng-style="{'background-image': 'url(' + blob.image + ')'}"/></div>
    <div id="playerDetails">
      <h1>[[ blob.title | words:5 ]]</h1>
      <div id="playerControls">
        <i class="fa fa-step-backward" ng-click="playlist.previous()" title="{% trans 'Backward' %}"></i>
        <i class="fa fa-play" ng-click="playlist.play()" ng-if="!playlist.playing" title="{% trans 'Play' %}"></i>
        <i class="fa fa-pause" ng-click="playlist.pause()" ng-if="playlist.playing" title="{% trans 'Pause' %}"></i>
        <i class="fa fa-step-forward" ng-click="playlist.next()" title="{% trans 'Forward' %}"></i>
        <p id="playerTimer">[[ time | secondsToDate | date: 'HH:mm:ss' ]]</p>
        <input id="volumeSlide" type="range" min="0" max="1" step="0.1"
        ng-model="volume"
        ng-change="setVolume(volume)"
        title="{% trans 'Volume' %}"></input>
        <a ng-if="blob.podcast" href="[[ blob.podcast ]]" title="{% trans 'Link' %}"><i class="fa fa-share"></i></a>
        <a ng-if="blob.url" href="[[ blob.url ]]" title="{% trans 'Download' %}"><i class="fa fa-download"></i></a>
      </div>
      <i id="playlistDown" class="fa fa-chevron-down" title="{% trans 'Playlist' %}"
        ng-click="playlistDown = !playlistDown"
        ng-class="{'fa-chevron-up': playlistDown, 'fa-chevron-down': !playlistDown}"></i>
    </div>
  </div>

  <ul id="playlist" ng-init="playlistDown = false" ng-show="playlistDown">
    <li class="playlistItem"
      ng-repeat="blob in playlist.queue track by $index"
      ng-class="{'current': $index == playlist.track}"
      ng-drag="true"
      ng-drop="true"
      ng-drag-data="[[ $index ]]"
      ng-drop-success="onDropComplete($event, $data, $index)"
      >
      <h1>[[ blob.title ]]</h1>
      <span class="playlistControls">
        <i class="fa fa-play" ng-click="playlist.play($index);" title="{% trans 'Play' %}"></i>
        <a ng-href="[[ blob.url ]]" title="{% trans 'Download' %}"><i class="fa fa-download"></i></a>
        <a ng-href="[[ blob.podcast ]]" title="{% trans 'Link' %}"><i class="fa fa-share"></i></a>
        <i class="fa fa-trash-o" ng-click="playlist.remove($index);" title="{% trans 'Remove' %}"></i>
        <i ng-drag-handle class="fa fa-arrows" title="{% trans 'Move' %}"></i>
      </span>
    </li>
  </ul>
</div>

antxetamedia/templates/podcast_control.html
{% load i18n static compress %}

<div class="podcastControl">
  {% if podcast.blob_set.with_content.exists %}
  <a class="play" data-podcast="{{ podcast.get_blobs_url }}"><i class="fa fa-play"></i></a>
  <a class="append" data-podcast="{{ podcast.get_blobs_url }}"><i class="fa fa-plus"></i></a>
  {% for blob in podcast.blob_set.select_related %}
  <a class="download" href="{{ blob.link }}"><i class="fa fa-download"></i></a>
  {% endfor %}
  {% endif %}
</div>